from agent_framework import Agent, Skill, MCPStdioTool
import json
import os
from skills.requirements_skill.requirements_skill import requirements_skill
from skills.structure_skill.structure_skill import structure_skill
from skills.java_skill.java_skill import java_skill
from tools.write_file import write_file
import base64

class MicroserviceAgent:

    def __init__(self, agent: Agent):
        self.agent = agent

    async def run_skill(self, skill: Skill, input_text: str):
        prompt = f"""
EXECUTE THE SKILL EXACTLY.

OUTPUT RULES - MUST FOLLOW:
NO explanations
NO markdown
NO comments
NO natural language
ONLY the raw file content

SKILL INSTRUCTIONS:
{skill.content}

INPUT:
{input_text}

OUTPUT:
ONLY the file content.
"""
        response = await self.agent.run(prompt)
        return response.text.strip()

    def safe_json(self, text):
        return json.loads(text)

    async def push_to_github(self, repo_name: str, generated_files: list):
        """Push generated files to GitHub using MCP directly."""

        github_username = os.getenv("GITHUB_USERNAME")

        async with MCPStdioTool(
            name="github",
            command="npx",
            args=["-y", "@modelcontextprotocol/server-github"],
            env={"GITHUB_PERSONAL_ACCESS_TOKEN": os.getenv("GITHUB_PERSONAL_ACCESS_TOKEN")},
            load_tools=True,
            load_prompts=False
        ) as github:

            print(f"Creating repository '{repo_name}'...")
            try:
                await github.call_tool(
                    "create_repository",
                    name=repo_name,
                    description=f"Microservice: {repo_name}",
                    private=False,
                    autoInit=True
                )
                print("Repo created")
            except Exception as e:
                print(f"Repo may already exist: {e}")

            print("Initializing main branch...")
            try:
                await github.call_tool(
                    "create_or_update_file",
                    owner=github_username,
                    repo=repo_name,
                    path=".gitkeep",
                    message="chore: initialize repository",
                    content=base64.b64encode(b"").decode("utf-8"),
                    branch="main"
                )
                print("Branch initialized")
            except Exception as e:
                print(f"Branch may already exist: {e}")

            print(f"Pushing {len(generated_files)} files...")
            res = await github.call_tool(
                "push_files",
                owner=github_username,
                repo=repo_name,
                branch="main",
                files=generated_files,
                message="feat: initial microservice generated by agent"
            )
            print("PUSH SUCCESS")
            print(res)

    async def generate(self, markdown: str):

        generated_files = []

        print("STEP 1 — PARSE REQUIREMENTS")
        req = await self.run_skill(requirements_skill(), markdown)
        requirements = self.safe_json(req)

        service_name = requirements["service_name"].lower().replace(" ", "-")

        print("STEP 2 — STRUCTURE")
        struct = await self.run_skill(structure_skill(), json.dumps(requirements))
        structure = self.safe_json(struct)

        base_dir = structure["base_dir"].replace("<service>", service_name)
        package = structure["package"].replace("<service>", service_name)
        package_path = package.replace(".", "/")

        print("STEP 3 — GENERATE FILES")
        for f in structure["files"]:
            file_path = (
                f["path"]
                .replace("<service>", service_name)
                .replace("<package_path>", package_path)
            )

            print("→", file_path)

            code = await self.run_skill(
                java_skill(),
                json.dumps({
                    "requirements": requirements,
                    "file": f,
                    "package": package
                })
            )

            full_path = os.path.join(base_dir, file_path)
            write_file(full_path, code)

            generated_files.append({
                "path": file_path,
                "content": code
            })

        print("STEP 4 — PUSH TO GITHUB")

        await self.push_to_github(
            repo_name=service_name,
            generated_files=generated_files
        )

        print(f"\nMICROSERVICE '{service_name}' GENERATED + PUSHED TO GITHUB")
